apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::517315340481:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CL8GCO8B1CM1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::517315340481:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-15T14:17:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "816"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 731906b4-736b-479a-a6db-516b82b14dce
