apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters

    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::517315340481:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1C5O9M2Y2ETHC
      username: system:node:{{EC2PrivateDNSName}}
     
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-15T09:40:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "865"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f439a1b6-ca0e-4aef-906f-1a27189718fc
